export interface BallotDao {
    id: number,
    countingUserId: number,
    additionalPeople: string | undefined | null,
    dateCreatedUtc: string,
    electionId: number,
    ballotStation: string | undefined | null,
    ballotIdentifier: string | undefined | null,
    isValid: boolean,
    notes: string | undefined | null,
    isDeleted: boolean,
    deleteUserId: number,
    deleteReason: string | undefined | null,
    deleteDateUtc: string,
}

// id               INTEGER PRIMARY KEY AUTOINCREMENT,
// countingUserId   INTEGER NOT NULL,
// additionalPeople TEXT NULL,
// dateCreated      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
// electionId       INTEGER NOT NULL,
// ballotStation    TEXT NULL,
// ballotIdentifier TEXT NULL,
// isValid          INTEGER NOT NULL,
// notes            TEXT NULL,
// isDeleted        INTEGER NOT NULL DEFAULT 0,
// deleteUserId     INTEGER NULL,
// deleteReason     TEXT NULL,
// deleteDateUtc    DATETIME NULL,
